"""
Dashboard Data Service — reads summary.json, source_index.json, and
pipeline health data to serve the frontend dashboard widgets.
"""

import os
import json
import logging
from typing import Dict, List, Optional
from datetime import datetime

logger = logging.getLogger(__name__)

# Resolve project root (5 levels up from this file)
_HERE = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.normpath(os.path.join(_HERE, "..", "..", "..", "..", ".."))

REPORTS_DIR = os.path.join(_PROJECT_ROOT, "results", "reports")
DAILY_DIR = os.path.join(_PROJECT_ROOT, "results", "daily")
META_DIR = os.path.join(_PROJECT_ROOT, "results", "metadata")
HITL_DIR = os.path.join(_PROJECT_ROOT, "data", "hitl_review")


class DashboardDataService:
    """Serves pre-computed pipeline output to the frontend dashboard."""

    def get_summary(self) -> Optional[Dict]:
        """Return the latest summary.json generated by the pipeline."""
        path = os.path.join(REPORTS_DIR, "summary.json")
        if not os.path.exists(path):
            return None
        try:
            with open(path, encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            logger.error(f"[DashboardData] summary.json read failed: {e}")
            return None

    def get_source_distribution(self) -> Dict[str, int]:
        """
        Parse source_index.json and return { source_platform: count }.
        Powers the dashboard pie/bar chart of content sources.
        """
        path = os.path.join(REPORTS_DIR, "source_index.json")
        if not os.path.exists(path):
            return {}
        try:
            with open(path, encoding="utf-8") as f:
                sources = json.load(f)

            dist: Dict[str, int] = {}
            for src in sources:
                platform = src.get("source_platform", "Unknown")
                dist[platform] = dist.get(platform, 0) + 1
            return dict(sorted(dist.items(), key=lambda x: x[1], reverse=True))
        except Exception as e:
            logger.error(f"[DashboardData] source_index.json read failed: {e}")
            return {}

    def get_pipeline_health(self) -> Dict:
        """
        Aggregate pipeline health from:
        - Most recent session metadata
        - HITL pending review count
        - Reports existence check
        """
        health: Dict = {
            "status": "unknown",
            "last_run": None,
            "reports_generated": [],
            "hitl_pending": 0,
            "total_sessions": 0,
        }

        # Check reports
        report_files = {
            "pdf": "report.pdf",
            "pptx": "report.pptx",
            "podcast_mp3": "podcast.mp3",
            "summary_json": "summary.json",
            "email_html": "email_report.html",
            "transcript": "transcript.txt",
        }
        for fmt, fname in report_files.items():
            fpath = os.path.join(REPORTS_DIR, fname)
            if os.path.exists(fpath):
                stat = os.stat(fpath)
                health["reports_generated"].append({
                    "format": fmt,
                    "file": fname,
                    "size_bytes": stat.st_size,
                    "modified_at": datetime.fromtimestamp(stat.st_mtime).isoformat(),
                })

        # Latest session metadata
        if os.path.exists(META_DIR):
            meta_files = sorted(
                [f for f in os.listdir(META_DIR) if f.startswith("meta_")],
                reverse=True,
            )
            health["total_sessions"] = len(meta_files)
            if meta_files:
                try:
                    with open(os.path.join(META_DIR, meta_files[0]), encoding="utf-8") as f:
                        latest = json.load(f)
                    health["last_run"] = latest.get("timestamp")
                    health["last_session"] = latest
                except Exception:
                    pass

        # HITL pending reviews
        pending_dir = os.path.join(HITL_DIR, "pending")
        if os.path.exists(pending_dir):
            health["hitl_pending"] = len(
                [f for f in os.listdir(pending_dir) if f.endswith(".json")]
            )

        # Overall status
        if health["last_run"]:
            health["status"] = "healthy"
        elif health["total_sessions"] == 0:
            health["status"] = "no_data"
        else:
            health["status"] = "stale"

        return health

    def get_trend_data(self, days: int = 30) -> List[Dict]:
        """
        Return daily paper counts from session metadata for trend charting.
        """
        if not os.path.exists(META_DIR):
            return []

        daily: Dict[str, int] = {}
        for fname in os.listdir(META_DIR):
            if not fname.startswith("meta_"):
                continue
            try:
                with open(os.path.join(META_DIR, fname), encoding="utf-8") as f:
                    meta = json.load(f)
                ts = meta.get("timestamp", "")[:10]  # YYYY-MM-DD
                if ts:
                    daily[ts] = daily.get(ts, 0) + meta.get("total_papers", 0)
            except Exception:
                continue

        return [
            {"date": date, "papers": count}
            for date, count in sorted(daily.items())
        ]
